"""
Generates database/seed_supabase.sql from the same SEED_COMPANIES data
build_db.py uses for the local SQLite prototype, so the two never drift.

Run: python3 database/export_supabase_seed.py

Paste the output file into the Supabase SQL editor (after schema_supabase.sql)
to load the 6 real portfolio companies and their reported monthly numbers
into a live Supabase project. It intentionally does *not* insert into
`scores`/`score_history` — that's Assignment 2's job (running the formula
against these rows and checking the result by hand).
"""

import os

from build_db import SEED_COMPANIES

OUT_PATH = os.path.join(os.path.dirname(__file__), "seed_supabase.sql")


def _sql_str(value):
    return "'" + value.replace("'", "''") + "'"


def generate_sql():
    lines = [
        "-- Generated by database/export_supabase_seed.py — do not hand-edit.",
        "-- Loads the 6 real portfolio companies + their monthly_metrics reports.",
        "",
    ]

    for company in SEED_COMPANIES:
        lines.append(
            "INSERT INTO companies (name, industry, founded_year) VALUES "
            f"({_sql_str(company['name'])}, {_sql_str(company['industry'])}, "
            f"{company['founded_year']});"
        )

    lines.append("")

    for company in SEED_COMPANIES:
        for report_date, revenue, burn_rate, cash_balance, growth_rate in company["metrics"]:
            runway_months = round(cash_balance / burn_rate, 4)
            lines.append(
                "INSERT INTO monthly_metrics "
                "(company_id, report_date, revenue, burn_rate, cash_balance, "
                "runway_months, growth_rate) VALUES ("
                f"(SELECT id FROM companies WHERE name = {_sql_str(company['name'])}), "
                f"{_sql_str(report_date)}, {revenue}, {burn_rate}, {cash_balance}, "
                f"{runway_months}, {growth_rate});"
            )

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sql = generate_sql()
    with open(OUT_PATH, "w") as f:
        f.write(sql)
    print(f"Wrote {OUT_PATH}")
