-- Generated by database/export_supabase_seed.py — do not hand-edit.
-- Loads the 6 real portfolio companies + their monthly_metrics reports.

INSERT INTO companies (name, industry, founded_year) VALUES ('NexaHealth', 'Healthcare', 2020);
INSERT INTO companies (name, industry, founded_year) VALUES ('GridLock AI', 'Cybersecurity', 2021);
INSERT INTO companies (name, industry, founded_year) VALUES ('PathWise', 'AI / ML Infrastructure', 2022);
INSERT INTO companies (name, industry, founded_year) VALUES ('SolarVault', 'Clean Energy', 2019);
INSERT INTO companies (name, industry, founded_year) VALUES ('Cognify Health', 'Healthcare', 2020);
INSERT INTO companies (name, industry, founded_year) VALUES ('VaultNet', 'Cybersecurity', 2018);

INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'NexaHealth'), '2026-04-01', 120000, 140000, 735000, 5.25, 0.02);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'NexaHealth'), '2026-05-01', 118000, 145000, 708000, 4.8828, -0.017);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'NexaHealth'), '2026-06-01', 112000, 150000, 670000, 4.4667, -0.051);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'NexaHealth'), '2026-07-01', 105000, 155000, 620000, 4.0, -0.063);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'GridLock AI'), '2026-04-01', 200000, 210000, 1672000, 7.9619, 0.01);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'GridLock AI'), '2026-05-01', 195000, 215000, 1652000, 7.6837, -0.025);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'GridLock AI'), '2026-06-01', 188000, 220000, 1620000, 7.3636, -0.036);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'GridLock AI'), '2026-07-01', 180000, 225000, 1575000, 7.0, -0.044);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'PathWise'), '2026-04-01', 2800000, 900000, 12250000, 13.6111, 0.14);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'PathWise'), '2026-05-01', 3200000, 950000, 14500000, 15.2632, 0.143);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'PathWise'), '2026-06-01', 3600000, 1000000, 17100000, 17.1, 0.125);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'PathWise'), '2026-07-01', 3900000, 1050000, 19950000, 19.0, 0.1);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'SolarVault'), '2026-04-01', 1900000, 700000, 7020000, 10.0286, 0.09);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'SolarVault'), '2026-05-01', 2050000, 720000, 8350000, 11.5972, 0.079);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'SolarVault'), '2026-06-01', 2200000, 740000, 9810000, 13.2568, 0.073);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'SolarVault'), '2026-07-01', 2350000, 760000, 11400000, 15.0, 0.068);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'Cognify Health'), '2026-04-01', 850000, 520000, 11005000, 21.1635, 0.045);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'Cognify Health'), '2026-05-01', 880000, 530000, 11355000, 21.4245, 0.035);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'Cognify Health'), '2026-06-01', 905000, 540000, 11720000, 21.7037, 0.028);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'Cognify Health'), '2026-07-01', 930000, 550000, 12100000, 22.0, 0.028);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'VaultNet'), '2026-04-01', 1200000, 650000, 14200000, 21.8462, 0.05);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'VaultNet'), '2026-05-01', 1260000, 660000, 13600000, 20.6061, 0.05);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'VaultNet'), '2026-06-01', 1320000, 670000, 12950000, 19.3284, 0.048);
INSERT INTO monthly_metrics (company_id, report_date, revenue, burn_rate, cash_balance, runway_months, growth_rate) VALUES ((SELECT id FROM companies WHERE name = 'VaultNet'), '2026-07-01', 1390000, 680000, 12240000, 18.0, 0.053);
