"""Populate news_watch/news.db with realistic-looking demo news items.

This sandbox can't reach live RSS/NewsAPI/SEC hosts (blocked by egress
policy), so this script exists purely to make the dashboard demoable.
It is NOT part of the real pipeline — once you run fetch_news.py somewhere
with normal internet access, real items will accumulate alongside (or
instead of) this seed data.

Usage:
    ./venv/bin/python -m news_watch.seed_demo_data
"""

import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from news_watch import db
from news_watch.config import COMPANIES

now = datetime.utcnow()

# (company_id, source, source_name, headline, matched_term, is_competitor, hours_ago, snippet)
DEMO_ITEMS = [
    ("nexahealth", "rss", "TechCrunch", "Teladoc reports quarterly earnings miss", "Teladoc", True, 2,
     "Teladoc Health reported quarterly results that fell short of Wall Street expectations, with revenue growth continuing to slow across its virtual care and chronic condition management segments. Management pointed to softer enterprise renewals and pricing pressure from lower-cost telehealth entrants as key drags on the quarter. The company also flagged elevated member acquisition costs, which compressed margins even as visit volumes held roughly steady year over year. Executives reiterated full-year guidance but acknowledged the recovery in profitability is taking longer than previously projected. Investors reacted negatively, with the stock declining sharply in after-hours trading as analysts questioned Teladoc's path back to sustained growth."),
    ("nexahealth", "newsapi", "Reuters", "Hims & Hers faces FDA scrutiny over compounded drugs", "Hims & Hers", True, 7,
     "Hims & Hers is facing heightened regulatory scrutiny after the FDA raised concerns about the company's use of compounded versions of popular weight-loss and hormone therapy drugs. Regulators indicated that compounding pharmacies should only fill such prescriptions during official drug shortages, and questioned whether Hims & Hers' practices comply with that standard now that shortages for some GLP-1 medications have eased. The scrutiny threatens a significant slice of the company's telehealth revenue, which has leaned heavily on compounded alternatives to branded drugs. Hims & Hers has pushed back publicly, arguing its compounding practices are legally compliant and serve patients who need personalized dosing. The episode adds regulatory uncertainty to a business model that rivals and short sellers have already questioned."),
    ("nexahealth", "rss", "TechCrunch", "Cerebral settles lawsuit over prescribing practices", "lawsuit", True, 12,
     "Cerebral has agreed to settle a lawsuit alleging the company's platform encouraged clinicians to prescribe controlled substances, including stimulants for ADHD, without adequate clinical oversight. The settlement resolves claims that rapid, volume-driven prescribing practices prioritized growth over patient safety during the company's pandemic-era expansion. As part of the agreement, Cerebral is expected to pay damages and implement stricter prescribing protocols and clinician review processes. The case is one of several legal and regulatory challenges the company has faced since regulators began scrutinizing telehealth prescribing of controlled substances more broadly. The resolution removes a legal overhang but underscores the compliance risks facing telehealth providers that prescribe regulated medications remotely."),
    ("nexahealth", "rss", "Crunchbase News", "Amwell announces new funding round", "Amwell", True, 17,
     "Amwell has closed a new funding round aimed at extending its runway as it continues to reposition itself around enterprise and health-system partnerships rather than direct-to-consumer telehealth. The fresh capital will reportedly support continued investment in Amwell's Converge platform, which integrates virtual and in-person care workflows for hospital clients. The round comes as the broader telehealth sector consolidates, with several smaller players exiting or merging amid slowing post-pandemic demand. Amwell's leadership has framed the raise as validation of its enterprise-first strategy, distinguishing it from consumer telehealth peers still struggling with unit economics. The additional funding gives the company more time to prove out that pivot before needing to return to capital markets."),
    ("nexahealth", "rss", "Ars Technica", "Telehealth clinical trial shows promising results", "clinical trial", False, 25,
     "A new clinical trial evaluating a telehealth-delivered treatment protocol has reported encouraging early results, with patient outcomes comparable to in-person care across several measured endpoints. Researchers noted particularly strong adherence rates among patients in rural or underserved areas who would otherwise face long travel times to see a specialist. The trial's authors suggested the findings could support broader insurance reimbursement for remote care models in the conditions studied. While the sample size was relatively modest, the results add to a growing body of evidence supporting telehealth as a clinically viable alternative for certain chronic condition management programs. Full trial data is expected to be published in a peer-reviewed journal later this year."),

    ("gridlock", "rss", "The Verge", "CrowdStrike discloses vulnerability in endpoint agent", "vulnerability", True, 3,
     "CrowdStrike disclosed a vulnerability in its endpoint detection agent that could, under specific conditions, allow an attacker with local access to escalate privileges on an affected machine. The company said it has already shipped a patch and found no evidence the flaw was exploited in the wild before discovery. Security researchers who reviewed the disclosure characterized the issue as serious but noted the practical exploitation requirements limit real-world risk for most customers. CrowdStrike urged customers to apply the update promptly and reiterated its standard responsible-disclosure and bug-bounty practices. The disclosure comes as endpoint security vendors face increased scrutiny over agent-level vulnerabilities following high-profile incidents across the industry this year."),
    ("gridlock", "sec_edgar", "SEC EDGAR", "Palo Alto Networks Inc filed 8-K mentioning \"Palo Alto Networks\"", "Palo Alto Networks", True, 8,
     "Palo Alto Networks filed a Form 8-K with the SEC disclosing a material event that the company was required to report under federal securities regulations. The filing does not specify the exact nature of the triggering event beyond referencing the company by name in the full-text search that surfaced it. 8-K filings are typically used to disclose items such as leadership changes, material agreements, acquisitions, restructuring actions, or other events investors would consider significant. Because this summary is generated from filing metadata rather than the filing's full body text, the specific substance of the disclosure should be confirmed by reviewing the actual document on EDGAR. Investors and analysts often monitor 8-K filings closely as an early signal of corporate developments ahead of formal earnings releases."),
    ("gridlock", "rss", "TechCrunch", "SentinelOne raises new funding round", "funding round", True, 13,
     "SentinelOne has closed a new funding round as it continues to scale its AI-driven endpoint and cloud security platform against larger rivals in the crowded cybersecurity market. The capital is expected to support continued investment in the company's autonomous threat detection and response capabilities, an area where it has positioned itself as a technology leader. The raise comes amid a broader wave of enterprise security funding as organizations increase spending in response to more sophisticated ransomware and nation-state threats. Analysts noted the round strengthens SentinelOne's competitive position without immediately changing the pecking order among the largest endpoint security vendors. The company's leadership framed the funding as fuel for accelerating go-to-market expansion rather than a signal of near-term acquisition interest."),
    ("gridlock", "newsapi", "Reuters", "Okta faces lawsuit over 2025 breach disclosure", "lawsuit", True, 19,
     "Okta is facing a lawsuit alleging the company delayed or inadequately disclosed details of a 2025 security breach affecting customer support systems, in violation of securities and consumer protection laws. Plaintiffs claim the delayed disclosure caused financial harm to shareholders and left affected customers exposed for longer than necessary. Okta has defended its disclosure timeline, stating it followed standard incident response and legal disclosure procedures once the scope of the breach was confirmed. The case adds to a pattern of increased litigation risk facing identity and access management vendors following a string of high-profile breaches across the sector. The outcome could influence how quickly security vendors are expected to disclose incidents to customers and investors going forward."),
    ("gridlock", "rss", "Ars Technica", "Ransomware group claims new victim among Fortune 500", "ransomware", False, 22,
     "A prominent ransomware group has claimed responsibility for compromising a Fortune 500 company, posting stolen data samples on its leak site as proof of the intrusion. The targeted company has not yet confirmed the full scope of the breach publicly, though incident response efforts are reportedly underway. Security researchers tracking the group note it has escalated its targeting of large enterprises in recent months, often demanding multimillion-dollar ransoms under threat of public data release. The incident adds to a growing tally of high-profile ransomware attacks this year and is likely to renew industry debate over ransom payment policies and cyber insurance coverage. Details of the attack vector and full impact are expected to emerge as the investigation progresses."),

    ("pathwise", "rss", "VentureBeat", "OpenAI announces new foundation model with longer context", "OpenAI", True, 1,
     "OpenAI has announced a new foundation model featuring a significantly extended context window, allowing it to process and reason over much larger documents and conversations in a single pass. The company says the expanded context length improves performance on tasks like long-document summarization, codebase analysis, and multi-turn reasoning that previously required workarounds like chunking or retrieval. Early benchmarks shared by OpenAI show meaningful gains on long-context evaluation suites compared to the prior generation of models. The announcement intensifies competition among leading AI labs, several of which have been racing to extend context windows and improve long-context reliability over the past year. Enterprise customers are expected to be a key focus for the release, given the model's applicability to large-scale document review and analysis workflows."),
    ("pathwise", "newsapi", "The Verge", "Anthropic raises Series C at higher valuation", "Anthropic", True, 6,
     "Anthropic has closed a new funding round at a markedly higher valuation than its previous raise, reflecting continued investor enthusiasm for frontier AI labs despite a broader tightening in venture funding elsewhere. The capital is expected to fund continued scaling of compute infrastructure and research toward more capable and safer large language models. The round reinforces Anthropic's position as one of the best-funded competitors to OpenAI in the race to develop increasingly capable foundation models. Investors participating in the round reportedly include a mix of existing backers and new strategic partners seeking exposure to the AI infrastructure buildout. The higher valuation underscores how competitive and capital-intensive the frontier AI model market has become."),
    ("pathwise", "rss", "TechCrunch", "Scale AI acquired by data labeling rival", "acquisition", True, 11,
     "Scale AI has been acquired by a rival data labeling and annotation company in a deal that consolidates two of the largest players in the data infrastructure market for training AI models. The acquisition is expected to combine Scale's enterprise and government customer relationships with the acquirer's technology stack, creating a larger combined platform for data curation and model evaluation services. Terms of the deal were not fully disclosed, though industry observers characterized it as one of the largest consolidations yet in the AI data services space. The combined company is expected to compete more aggressively for large enterprise and government contracts that require high-quality labeled training data. The deal reflects growing consolidation pressure in the data labeling market as demand shifts toward more specialized, higher-margin evaluation and red-teaming services."),
    ("pathwise", "rss", "Ars Technica", "Databricks reports data breach affecting enterprise customers", "data breach", True, 18,
     "Databricks disclosed a data breach affecting a subset of its enterprise customers, following unauthorized access to systems containing customer configuration and usage data. The company said it has notified affected customers directly and is working with external security firms to investigate the scope and root cause of the incident. Early indications suggest the breach did not expose customers' underlying data lake contents, though the full extent of exposed metadata is still being assessed. Databricks has pledged to publish a detailed post-incident report once the investigation concludes and has begun rolling out additional access control safeguards. The disclosure adds to a string of data platform security incidents this year that have heightened enterprise scrutiny of vendor security practices before signing new contracts."),
    ("pathwise", "rss", "Crunchbase News", "Hugging Face partnership brings open models to enterprise", "Hugging Face", True, 24,
     "Hugging Face has announced a new enterprise partnership aimed at making its catalog of open-source models more accessible to large organizations seeking alternatives to closed, proprietary AI systems. The partnership is expected to include managed hosting, compliance tooling, and support services designed to ease enterprise adoption of open models in regulated industries. Hugging Face has positioned open-weight models as a cost-effective and more transparent alternative to closed foundation models from larger AI labs. The move reflects broader enterprise interest in maintaining more control over model weights, fine-tuning, and data governance than proprietary API-based models typically allow. Analysts see the partnership as part of a broader trend of open-source AI providers building enterprise-grade offerings to compete for large contracts historically dominated by closed-model vendors."),
    ("pathwise", "newsapi", "Reuters", "GPU shortage continues to squeeze AI infra startups", "GPU", False, 30,
     "A persistent shortage of high-end GPUs continues to constrain growth for AI infrastructure startups, many of which report multi-month waitlists for the compute capacity needed to train and serve large models. Smaller companies say they are increasingly priced out of reserved capacity as large AI labs and cloud providers lock up supply through long-term contracts. The shortage has pushed some startups to explore alternative chip architectures or renting capacity from smaller regional data center operators as a stopgap. Industry analysts expect supply to gradually improve as chipmakers ramp production, but caution that demand from frontier model training is likely to keep the market tight in the near term. The dynamic is reshaping competitive positioning across the AI infrastructure sector, favoring well-capitalized players who secured compute commitments early."),

    ("solarvault", "rss", "TechCrunch", "Sunrun reports strong quarterly installs", "Sunrun", True, 4,
     "Sunrun reported quarterly solar installation volumes that beat analyst expectations, citing continued demand for residential solar-plus-storage systems despite higher interest rates weighing on the broader home improvement market. The company attributed the growth to expanded storage attachment rates, as more customers pair solar panels with battery systems for backup power and demand-charge management. Management highlighted improving unit economics as financing costs stabilize and the company shifts more of its portfolio toward cash and loan sales rather than leases. Despite the strong installation numbers, Sunrun reiterated caution around near-term margins given ongoing policy uncertainty around net metering rules in key state markets. The results were seen as a positive signal for the residential solar sector after several quarters of demand softness industry-wide."),
    ("solarvault", "rss", "Crunchbase News", "Tesla Energy announces new battery storage partnership", "Tesla Energy", True, 10,
     "Tesla Energy has announced a new partnership to expand deployment of its grid-scale battery storage systems, extending its footprint beyond residential Powerwall installations into larger utility and commercial projects. The partnership is expected to combine Tesla's Megapack technology with the partner's project development and grid interconnection expertise to accelerate deployment timelines. Tesla Energy has increasingly become a meaningful growth driver for the broader company as automotive margins have come under pressure, making storage partnerships strategically important. The deal adds to a string of large storage contracts Tesla has announced this year as utilities race to add grid flexibility amid rising renewable penetration. Analysts view the partnership as reinforcing Tesla's position as one of the largest suppliers of grid-scale battery storage globally."),
    ("solarvault", "newsapi", "Reuters", "SunPower lays off staff amid sector slowdown", "layoffs", True, 16,
     "SunPower announced layoffs affecting a meaningful portion of its workforce as the broader residential solar sector grapples with slowing demand amid higher financing costs and reduced state-level incentives. The company said the cuts are part of a broader restructuring intended to preserve cash and align headcount with a more conservative near-term installation outlook. SunPower has faced mounting financial pressure over the past year, including questions about its liquidity position and ability to fund growth without additional capital. The layoffs follow similar workforce reductions at other residential solar installers as the sector works through a post-incentive-era demand reset. Analysts will be watching upcoming results closely for signs of whether the cost cuts are sufficient to stabilize the company's financial position."),
    ("solarvault", "rss", "VentureBeat", "Enphase Energy raises new funding round", "funding round", True, 23,
     "Enphase Energy has secured new funding aimed at supporting continued investment in its microinverter and battery storage product lines as competition in the residential solar equipment market intensifies. The capital is expected to fund expanded manufacturing capacity as the company works to qualify for domestic content incentives tied to recent energy policy legislation. Enphase has faced margin pressure over the past year as channel inventory corrections and softer installer demand weighed on shipment volumes. The funding gives the company additional flexibility to invest through the current demand trough without needing to significantly cut R&D spending. Management framed the raise as a bridge to an anticipated recovery in residential solar demand as financing conditions improve."),
    ("solarvault", "rss", "TechCrunch", "Solar sector sees renewed investor interest", "solar", False, 29,
     "Investor sentiment toward the solar sector has shown signs of improvement after a prolonged downturn driven by higher interest rates and policy uncertainty around clean energy incentives. Analysts point to stabilizing financing costs and clearer guidance on federal tax credit eligibility as key factors renewing interest in both residential and utility-scale solar equities. Several solar-focused funds have reported increased inflows in recent weeks, reversing a multi-quarter trend of outflows from the sector. Industry executives caution that a durable recovery will depend on sustained policy stability and continued improvement in project financing conditions. The renewed interest comes as several solar companies prepare to report quarterly results that will offer a clearer read on whether the sector's fundamentals are genuinely improving."),

    ("cognify", "rss", "TechCrunch", "Tempus acquires clinical data startup", "Tempus", True, 5,
     "Tempus has acquired a clinical data analytics startup in a deal aimed at expanding its access to structured real-world patient data used to power precision medicine and diagnostic products. The acquisition is expected to strengthen Tempus's data pipelines for oncology and other therapeutic areas where longitudinal patient data is critical for training predictive models. Terms of the deal were not disclosed, though the acquisition continues Tempus's strategy of bolt-on acquisitions to build out its data and AI diagnostics platform. The deal comes as competition intensifies among precision medicine companies racing to build the largest and most clinically useful real-world data assets. Analysts see the acquisition as consistent with Tempus's broader positioning as a data-driven diagnostics and therapeutics company rather than a pure-play lab testing provider."),
    ("cognify", "newsapi", "Reuters", "Komodo Health announces new funding round", "Komodo Health", True, 14,
     "Komodo Health has closed a new funding round to support continued expansion of its healthcare data platform, which maps real-world patient journeys for pharmaceutical, payer, and provider customers. The capital is expected to fund further investment in the company's data integration and analytics capabilities as demand grows for real-world evidence in drug development and commercialization. Komodo has positioned itself as a neutral data platform that can serve multiple stakeholders across the healthcare ecosystem, a differentiator it has emphasized to investors. The raise comes amid continued investor interest in healthcare data infrastructure companies, even as funding for earlier-stage digital health startups has cooled. Management framed the round as support for continued growth rather than a signal of any near-term public listing plans."),
    ("cognify", "rss", "Crunchbase News", "Innovaccer discloses data breach affecting customers", "data breach", True, 20,
     "Innovaccer disclosed a data breach affecting a number of its healthcare customers, following unauthorized access to systems that reportedly contained certain patient and operational data. The company said it has engaged third-party forensic investigators and notified affected customers and regulators as required under applicable healthcare privacy laws. Innovaccer has stated that it is implementing additional security controls in response to the incident, though the full scope of affected records has not yet been publicly detailed. The breach adds to a growing list of healthcare data platform incidents this year, intensifying scrutiny of vendor security practices among hospital and health system customers. Affected organizations may face their own regulatory notification obligations depending on the nature of the data involved, adding downstream compliance implications beyond Innovaccer itself."),
    ("cognify", "rss", "The Verge", "Butterfly Network reports diagnostics platform outage", "diagnostics", True, 26,
     "Butterfly Network experienced an outage affecting its cloud-connected point-of-care ultrasound diagnostics platform, temporarily disrupting access for some clinical customers. The company said the issue stemmed from a backend infrastructure failure rather than a security incident, and that patient data integrity was not affected. Butterfly Network restored service within the reported window and said it is implementing additional redundancy measures to reduce the risk of similar outages going forward. The incident highlights the operational risk healthcare providers take on when relying on cloud-connected diagnostic devices for point-of-care decision-making. Customers affected by the outage may seek service credits or assurances about platform reliability before renewing or expanding their deployments."),

    ("vaultnet", "rss", "TechCrunch", "Zscaler raises new funding round at higher valuation", "Zscaler", True, 1,
     "Zscaler has closed a new funding round at a higher valuation, reflecting continued investor confidence in the company's cloud-native zero trust security platform. The capital is expected to support continued investment in expanding Zscaler's global network of security enforcement points and further development of its AI-driven threat detection capabilities. The higher valuation comes despite a broader slowdown in enterprise security spending growth, underscoring Zscaler's relatively strong competitive position in the zero trust market. Analysts noted the raise strengthens Zscaler's ability to compete against both established network security vendors and newer zero trust entrants. Management framed the funding as support for accelerating platform expansion rather than a signal of near-term acquisition or IPO-adjacent activity."),
    ("vaultnet", "newsapi", "Reuters", "Cloudflare reports major outage affecting customers", "Cloudflare", True, 6,
     "Cloudflare experienced a major outage that disrupted access to a significant portion of the websites and applications relying on its network for content delivery, DNS, and security services. The company said the incident stemmed from a configuration error during a routine infrastructure update rather than an external attack. Cloudflare restored service within the disclosed window and committed to publishing a detailed post-incident report outlining the root cause and remediation steps. The outage renewed industry debate about the concentration risk created by a small number of infrastructure providers underpinning large portions of the internet. Affected customers are expected to press Cloudflare for additional service level guarantees and more resilient failover architecture following the incident."),
    ("vaultnet", "rss", "The Verge", "Fortinet acquires zero trust startup", "acquires", True, 15,
     "Fortinet has acquired a zero trust network access startup in a deal aimed at strengthening its security service edge product portfolio against larger cloud-native competitors. The acquisition is expected to accelerate Fortinet's roadmap for converging network and security functions into a single unified platform. Terms of the deal were not disclosed, though the acquisition continues a wave of consolidation among security vendors racing to offer comprehensive zero trust architectures. Fortinet has historically grown through a mix of organic development and targeted acquisitions to fill capability gaps in its platform. Analysts see the deal as a defensive move to keep pace with cloud-native competitors that have been gaining share in the zero trust access market."),
    ("vaultnet", "sec_edgar", "SEC EDGAR", "Rapid7 Inc filed 8-K mentioning \"Rapid7\"", "Rapid7", True, 21,
     "Rapid7 filed a Form 8-K with the SEC disclosing a material event that the company was required to report under federal securities regulations. The filing was surfaced through a full-text search matching the company's name and does not itself specify the exact nature of the underlying event. Companies typically file 8-Ks to disclose items such as executive changes, material agreements, restructuring actions, or other developments considered significant to investors. Because this summary is generated from filing metadata rather than the filing's full text, the specific substance of the disclosure should be confirmed by reviewing the document directly on EDGAR. Investors often treat 8-K filings as an early signal worth monitoring ahead of a company's next scheduled earnings report."),
    ("vaultnet", "rss", "Crunchbase News", "Zero trust security sees renewed funding round activity", "zero trust", False, 28,
     "Investor interest in zero trust security startups has picked up in recent weeks, with several companies in the space announcing new funding rounds after a relatively quiet stretch for cybersecurity venture funding. Analysts attribute the renewed activity to continued enterprise demand for modernizing network access architectures away from legacy perimeter-based security models. The funding rounds span a range of stages, from early-stage startups building niche access control products to more mature companies scaling go-to-market operations. Investors are reportedly favoring companies that can demonstrate clear differentiation in a crowded zero trust market rather than broad platform plays. The activity suggests cybersecurity remains one of the more resilient areas of enterprise software investment even as broader venture funding levels remain below their peak."),
]


def run():
    db.init_db()
    db.upsert_companies(COMPANIES)

    inserted = 0
    for i, (company_id, source, source_name, headline, matched_term, is_competitor, hours_ago, snippet) in enumerate(DEMO_ITEMS):
        published = now - timedelta(hours=hours_ago)
        new = db.insert_news_item(
            {
                "company_id": company_id,
                "source": source,
                "source_name": source_name,
                "author": None if source == "sec_edgar" else f"{source_name} Staff",
                "headline": headline,
                "url": f"https://example.com/demo-article-{i}",
                "published_at": published.strftime("%Y-%m-%dT%H:%M:%SZ"),
                "matched_term": matched_term,
                "is_competitor_mention": is_competitor,
                "snippet": snippet,
            }
        )
        if new:
            inserted += 1

    print(f"Seeded {inserted} demo news items across {len(COMPANIES)} companies.")


if __name__ == "__main__":
    run()
